import { Client, Property, CalendarEvent, Task, Sale, Rental, Document } from './types';

export const MOCK_CLIENTS: Client[] = [
  {
    id: 'c1',
    name: 'Juan Pérez',
    phone: '+5491144556677',
    email: 'juan.perez@email.com',
    type: 'comprador',
    status: 'interesado',
    origin: 'WhatsApp',
    budget: 150000,
    currency: 'USD',
    interestZone: 'Palermo',
    propertyTypeInterest: 'departamento',
    lastContact: '2024-05-10',
    notes: 'Busca departamento 3 ambientes con balcón.',
    createdAt: '2024-04-15'
  },
  {
    id: 'c2',
    name: 'María García',
    phone: '+5491122334455',
    email: 'm.garcia@email.com',
    type: 'vendedor',
    status: 'en seguimiento',
    origin: 'Web',
    interestZone: 'Belgrano',
    lastContact: '2024-05-11',
    notes: 'Vende PH en Belgrano R, necesita tasar.',
    createdAt: '2024-04-20',
    currency: 'USD'
  },
  {
    id: 'c3',
    name: 'Carlos Rodríguez',
    phone: '+5491155667788',
    email: 'crodriguez@email.com',
    type: 'inquilino',
    status: 'contactado',
    origin: 'Instagram',
    budget: 200000,
    currency: 'ARS',
    interestZone: 'Caballito',
    lastContact: '2024-05-09',
    notes: 'Busca alquiler zona Parque Centenario.',
    createdAt: '2024-05-01'
  },
  {
    id: 'c4',
    name: 'Lucía Fernández',
    phone: '+5491199887766',
    email: 'lfernandez@email.com',
    type: 'inversor',
    status: 'negociación',
    origin: 'Referido',
    budget: 300000,
    currency: 'USD',
    interestZone: 'Puerto Madero',
    lastContact: '2024-05-11',
    notes: 'Interesado en pozo o unidades rentables.',
    createdAt: '2023-12-10'
  },
  {
    id: 'c5',
    name: 'Roberto Sánchez',
    phone: '+5491133445566',
    email: 'rsanchez@email.com',
    type: 'propietario',
    status: 'cerrado',
    origin: 'Llamada',
    lastContact: '2024-05-05',
    notes: 'Propietario de la casa en Martínez.',
    createdAt: '2024-01-20',
    currency: 'USD'
  },
  {
    id: 'c6',
    name: 'Elena Martínez',
    phone: '+5491188776655',
    email: 'emartinez@email.com',
    type: 'interesado',
    status: 'nuevo',
    origin: 'Web',
    budget: 120000,
    currency: 'USD',
    interestZone: 'Recoleta',
    lastContact: '2024-05-11',
    notes: 'Consulta por depto en Av. Santa Fe.',
    createdAt: '2024-05-11'
  },
  {
    id: 'c7',
    name: 'Daniel López',
    phone: '+541122334455',
    email: 'dlopez@email.com',
    type: 'comprador',
    status: 'perdido',
    origin: 'Oficina',
    budget: 80000,
    currency: 'USD',
    interestZone: 'Almagro',
    lastContact: '2024-03-15',
    notes: 'Compró por otra inmobiliaria.',
    createdAt: '2024-02-10'
  },
  {
    id: 'c8',
    name: 'Sofia Wagner',
    phone: '+541199008877',
    email: 'swagner@email.com',
    type: 'vendedor',
    status: 'contactado',
    origin: 'WhatsApp',
    interestZone: 'Olivos',
    lastContact: '2024-05-08',
    notes: 'Quiere tasar depto 2 amb.',
    createdAt: '2024-05-05',
    currency: 'USD'
  }
];

export const MOCK_PROPERTIES: Property[] = [
  {
    id: 'p1',
    code: 'DEP-101',
    title: 'Moderno Departamento 3 Ambientes',
    type: 'departamento',
    operation: 'venta',
    status: 'disponible',
    address: 'Av. del Libertador 2400',
    zone: 'Palermo',
    city: 'CABA',
    price: 245000,
    currency: 'USD',
    rooms: 3,
    bedrooms: 2,
    bathrooms: 2,
    surface: 85,
    externalLink: 'https://ejemplo.com/prop1',
    externalSource: 'Zonaprop',
    notes: 'Excelente estado, luminoso.',
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800']
  },
  {
    id: 'p2',
    code: 'CAS-202',
    title: 'Casa Residencial con Parque',
    type: 'casa',
    operation: 'venta',
    status: 'disponible',
    address: 'Uruguay 1500',
    zone: 'Martínez',
    city: 'San Isidro',
    price: 450000,
    currency: 'USD',
    rooms: 5,
    bedrooms: 3,
    bathrooms: 3,
    surface: 250,
    externalLink: 'https://ejemplo.com/prop2',
    externalSource: 'Argenprop',
    notes: 'Piscina y quincho.',
    images: ['https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800']
  },
  {
    id: 'p3',
    code: 'DEP-303',
    title: 'Monoambiente Reformado',
    type: 'departamento',
    operation: 'alquiler',
    status: 'alquilada',
    address: 'Borges 1800',
    zone: 'Palermo Soho',
    city: 'CABA',
    price: 450000,
    currency: 'ARS',
    rooms: 1,
    bedrooms: 0,
    bathrooms: 1,
    surface: 32,
    notes: 'Ideal profesional.',
    images: ['https://images.unsplash.com/photo-1536376074432-bf121770998a?w=800']
  },
  {
    id: 'p4',
    code: 'LOC-404',
    title: 'Local Comercial Excelente Ubicación',
    type: 'local',
    operation: 'alquiler',
    status: 'disponible',
    address: 'Santa Fe 3200',
    zone: 'Recoleta',
    city: 'CABA',
    price: 1200000,
    currency: 'ARS',
    rooms: 2,
    bedrooms: 0,
    bathrooms: 1,
    surface: 45,
    notes: 'Doble vidriera.',
    images: ['https://images.unsplash.com/photo-1543007630-9710e4a00a20?w=800']
  },
  {
    id: 'p5',
    code: 'TER-505',
    title: 'Lote en Barrio Cerrado',
    type: 'terreno',
    operation: 'venta',
    status: 'reservada',
    address: 'Ruta 27 Km 5',
    zone: 'Nordelta',
    city: 'Tigre',
    price: 180000,
    currency: 'USD',
    rooms: 0,
    bedrooms: 0,
    bathrooms: 0,
    surface: 800,
    notes: 'Excelente orientación.',
    images: ['https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800']
  },
  {
    id: 'p6',
    code: 'DEP-606',
    title: 'Duplex con Terraza Propia',
    type: 'departamento',
    operation: 'venta',
    status: 'disponible',
    address: 'Dorrego 1200',
    zone: 'Chacarita',
    city: 'CABA',
    price: 165000,
    currency: 'USD',
    rooms: 3,
    bedrooms: 2,
    bathrooms: 2,
    surface: 75,
    notes: 'A estrenar.',
    images: ['https://images.unsplash.com/photo-1560448204-61dc36dc98c8?w=800']
  },
  {
    id: 'p7',
    code: 'OFI-707',
    title: 'Oficina Piso Completo',
    type: 'oficina',
    operation: 'alquiler',
    status: 'disponible',
    address: 'Corrientes 400',
    zone: 'Centro',
    city: 'CABA',
    price: 2500,
    currency: 'USD',
    rooms: 4,
    bedrooms: 0,
    bathrooms: 2,
    surface: 120,
    notes: 'Seguridad 24hs.',
    images: ['https://images.unsplash.com/photo-1497366216548-37526070297c?w=800']
  },
  {
    id: 'p8',
    code: 'DEP-808',
    title: 'Depto 2 Ambientes Caballito',
    type: 'departamento',
    operation: 'venta',
    status: 'vendida',
    address: 'Rivadavia 5400',
    zone: 'Caballito',
    city: 'CABA',
    price: 95000,
    currency: 'USD',
    rooms: 2,
    bedrooms: 1,
    bathrooms: 1,
    surface: 42,
    notes: 'Vendido rápido.',
    images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800']
  }
];

export const MOCK_EVENTS: CalendarEvent[] = [
  {
    id: 'e1',
    title: 'Visita Palermo',
    description: 'Mostrar depto a Juan Pérez',
    date: '2024-05-12',
    time: '10:00',
    type: 'visita',
    status: 'pendiente',
    clientId: 'c1',
    propertyId: 'p1',
    createdAt: '2024-05-10'
  },
  {
    id: 'e2',
    title: 'Tasación Belgrano',
    description: 'Tasar PH de María García',
    date: '2024-05-12',
    time: '12:30',
    type: 'tasación',
    status: 'pendiente',
    clientId: 'c2',
    createdAt: '2024-05-10'
  },
  {
    id: 'e3',
    title: 'Firma de Reserva',
    description: 'Reserva Nordelta',
    date: '2024-05-13',
    time: '15:00',
    type: 'firma',
    status: 'pendiente',
    clientId: 'c4',
    propertyId: 'p5',
    createdAt: '2024-05-10'
  },
  {
    id: 'e4',
    title: 'Llamada Seguimiento',
    description: 'Consultar por crédito hipotecario',
    date: '2024-05-11',
    time: '09:00',
    type: 'seguimiento',
    status: 'realizado',
    clientId: 'c1',
    createdAt: '2024-05-10'
  },
  {
    id: 'e5',
    title: 'Entrega de Llaves',
    description: 'Alquiler Palermo Soho',
    date: '2024-05-14',
    time: '11:00',
    type: 'entrega_de_llaves',
    status: 'pendiente',
    clientId: 'c3',
    propertyId: 'p3',
    createdAt: '2024-05-10'
  }
];

export const MOCK_TASKS: Task[] = [
  {
    id: 't1',
    title: 'Llamar a Juan Pérez',
    description: 'Consultar si le gustó la propiedad de Palermo',
    dueDate: '2024-05-13',
    priority: 'alta',
    status: 'pendiente',
    clientId: 'c1',
    createdAt: '2024-05-10'
  },
  {
    id: 't2',
    title: 'Subir fotos Nordelta',
    description: 'Fotos nuevas del lote',
    dueDate: '2024-05-11',
    priority: 'media',
    status: 'completada',
    propertyId: 'p5',
    createdAt: '2024-05-10'
  },
  {
    id: 't3',
    title: 'Enviar documentación escribano',
    description: 'Caso Elena Martínez',
    dueDate: '2024-05-11',
    priority: 'urgente',
    status: 'vencida',
    clientId: 'c6',
    createdAt: '2024-05-10'
  },
  {
    id: 't4',
    title: 'Pedir informes de dominio',
    description: 'Propiedad Martínez',
    dueDate: '2024-05-15',
    priority: 'media',
    status: 'pendiente',
    createdAt: '2024-05-10'
  },
  {
    id: 't5',
    title: 'Publicar en Instagram',
    description: 'Nuevos ingresos de la semana',
    dueDate: '2024-05-12',
    priority: 'baja',

    status: 'pendiente',
    createdAt: '2024-05-10'
  },
  {
    id: 't6',
    title: 'Revisar contratos vencidos',
    description: 'Chequear alquileres de Junio',
    dueDate: '2024-05-20',
    priority: 'media',
    status: 'pendiente',
    createdAt: '2024-05-10'
  },
  {
    id: 't7',
    title: 'Contactar Lucía Fernández',
    description: 'Nuevas oportunidades en Pozo',
    dueDate: '2024-05-13',
    priority: 'alta',
    status: 'pendiente',
    clientId: 'c4',
    createdAt: '2024-05-10'
  },
  {
    id: 't8',
    title: 'Actualizar precios',
    description: 'Ajustar precios por inflación',
    dueDate: '2024-05-10',
    priority: 'media',
    status: 'completada',
    createdAt: '2024-05-10'
  }
];

export const MOCK_SALES: Sale[] = [
  {
    id: 's1',
    clientCompradorId: 'c1',
    propiedadId: 'p1',
    propietarioId: 'c5',
    precioPublicado: 245000,
    precioOfrecido: 235000,
    comisionEstimada: 7050,
    moneda: 'USD',
    estado: 'negociación',
    notas: 'El comprador ofreció un 4% menos.',
    fechaCreacion: '2024-05-01',
    fechaActualizacion: '2024-05-10'
  },
  {
    id: 's2',
    clientCompradorId: 'c4',
    propiedadId: 'p5',
    propietarioId: 'c5',
    precioPublicado: 180000,
    precioOfrecido: 180000,
    precioAcordado: 180000,
    comisionEstimada: 5400,
    moneda: 'USD',
    fechaReserva: '2024-05-01',
    fechaEscritura: '2024-06-15',
    estado: 'reserva',
    notas: 'Reserva confirmada.',
    fechaCreacion: '2024-04-25',
    fechaActualizacion: '2024-05-01'
  },
  {
    id: 's3',
    clientCompradorId: 'c7',
    propiedadId: 'p8',
    propietarioId: 'c2',
    precioPublicado: 95000,
    precioAcordado: 92000,
    comisionEstimada: 2760,
    moneda: 'USD',
    estado: 'vendida',
    notas: 'Venta cerrada exitosamente.',
    fechaCreacion: '2024-03-10',
    fechaActualizacion: '2024-03-25'
  },
  {
    id: 's4',
    clientCompradorId: 'c6',
    propiedadId: 'p6',
    propietarioId: 'c8',
    precioPublicado: 165000,
    comisionEstimada: 4950,
    moneda: 'USD',
    estado: 'visita',
    notas: 'Interesada en segunda visita.',
    fechaCreacion: '2024-05-05',
    fechaActualizacion: '2024-05-05'
  }
];

export const MOCK_RENTALS: Rental[] = [
  {
    id: 'r1',
    inquilinoId: 'c3',
    propiedadId: 'p3',
    propietarioId: 'c5',
    montoMensual: 450000,
    deposito: 900000,
    comision: 450000,
    moneda: 'ARS',
    fechaInicio: '2023-10-01',
    fechaFin: '2025-09-30',
    diaPago: 5,
    estado: 'en curso',
    notas: 'Pago siempre puntual.',
    fechaCreacion: '2023-09-20',
    fechaActualizacion: '2023-10-01'
  },
  {
    id: 'r2',
    inquilinoId: 'c1',
    propiedadId: 'p4',
    propietarioId: 'c8',
    montoMensual: 1200000,
    deposito: 2400000,
    comision: 1200000,
    moneda: 'ARS',
    fechaInicio: '2024-06-01',
    fechaFin: '2026-05-31',
    diaPago: 10,
    estado: 'firmado',
    notas: 'Contrato comercial.',
    fechaCreacion: '2024-05-15',
    fechaActualizacion: '2024-05-20'
  },
  {
    id: 'r3',
    inquilinoId: 'c6',
    propiedadId: 'p7',
    propietarioId: 'c5',
    montoMensual: 2500,
    deposito: 5000,
    comision: 2500,
    moneda: 'USD',
    fechaInicio: '2024-01-15',
    fechaFin: '2026-01-14',
    diaPago: 1,
    estado: 'en curso',
    notas: 'Oficina.',
    fechaCreacion: '2024-01-05',
    fechaActualizacion: '2024-01-15'
  },
  {
    id: 'r4',
    inquilinoId: 'c4',
    propiedadId: 'p2',
    propietarioId: 'c2',
    montoMensual: 3500,
    deposito: 7000,
    comision: 3500,
    moneda: 'USD',
    fechaInicio: '2024-05-20',
    fechaFin: '2026-05-19',
    diaPago: 5,
    estado: 'documentación',
    notas: 'Esperando garantía de Alquiler.',
    fechaCreacion: '2024-05-10',
    fechaActualizacion: '2024-05-12'
  }
];

export const MOCK_DOCUMENTS: Document[] = [
  {
    id: 'd1',
    name: 'DNI Titular - PH Belgrano',
    type: 'DNI',
    status: 'revisado',
    clientId: 'c2',
    propertyId: 'p2',
    uploadDate: '2024-04-20',
    notes: 'DNI del propietario verificado',
    fileName: 'dni_titular_belgrano.pdf',
    fileSize: 245000,
    fileExtension: 'pdf',
    simulatedUrl: '/documents/d1'
  },
  {
    id: 'd2',
    name: 'Escritura Martínez',
    type: 'Escritura',
    status: 'cargado',
    clientId: 'c5',
    propertyId: 'p2',
    uploadDate: '2024-01-25',
    notes: 'Escritura original digitalizada',
    fileName: 'escritura_martinez.pdf',
    fileSize: 1240000,
    fileExtension: 'pdf',
    simulatedUrl: '/documents/d2'
  },
  {
    id: 'd3',
    name: 'Reserva Nordelta',
    type: 'Reserva',
    status: 'revisado',
    clientId: 'c4',
    propertyId: 'p5',
    saleId: 's2',
    uploadDate: '2024-05-02',
    notes: 'Reserva confirmada con seña del 10%',
    fileName: 'reserva_nordelta.pdf',
    fileSize: 520000,
    fileExtension: 'pdf',
    simulatedUrl: '/documents/d3'
  },
  {
    id: 'd4',
    name: 'Contrato Palermo Soho',
    type: 'Contrato',
    status: 'revisado',
    clientId: 'c3',
    propertyId: 'p3',
    rentalId: 'r1',
    uploadDate: '2023-09-28',
    notes: 'Contrato de alquiler por 2 años',
    fileName: 'contrato_palermo_soho.pdf',
    fileSize: 890000,
    fileExtension: 'pdf',
    simulatedUrl: '/documents/d4'
  },
  {
    id: 'd5',
    name: 'Recibo Depósito Palermo Soho',
    type: 'Recibo',
    status: 'cargado',
    clientId: 'c3',
    uploadDate: '2023-10-01',
    notes: 'Depósito de garantía abonado',
    fileName: 'recibo_deposito_soho.jpeg',
    fileSize: 180000,
    fileExtension: 'jpeg'
  },
  {
    id: 'd6',
    name: 'Garantía Alquiler Martínez',
    type: 'Garantía',
    status: 'pendiente',
    clientId: 'c4',
    uploadDate: '2024-05-10',
    notes: 'Esperando documentación del garante'
  },
  {
    id: 'd7',
    name: 'Boleto de Compraventa Nordelta',
    type: 'Boleto',
    status: 'pendiente',
    clientId: 'c4',
    propertyId: 'p5',
    saleId: 's2',
    uploadDate: '2024-05-15',
    notes: 'Boleto firmado por ambas partes, pendiente de escrituración'
  },
  {
    id: 'd8',
    name: 'Comprobante de Pago - Sr. Pérez',
    type: 'Comprobante',
    status: 'revisado',
    clientId: 'c1',
    saleId: 's1',
    uploadDate: '2024-05-12',
    notes: 'Transferencia bancaria de la seña confirmada',
    fileName: 'comprobante_pago_perez.png',
    fileSize: 320000,
    fileExtension: 'png'
  }
];
